import { NextRequest, NextResponse } from "next/server";
// @ts-ignore
import pptxgen from "pptxgenjs";

// ─── Colors ───────────────────────────────────────────────────────────────────
const C = {
  navy:       "1B3A6B",
  blue:       "2563EB",
  lightBlue:  "DBEAFE",
  teal:       "0891B2",
  white:      "FFFFFF",
  offWhite:   "F8FAFC",
  gray:       "64748B",
  lightGray:  "E2E8F0",
  darkText:   "1E293B",
  green:      "059669",
  amber:      "D97706",
  red:        "DC2626",
  quadLeader: "1B3A6B",
  quadChall:  "7C3AED",
  quadNiche:  "DB2777",
  quadEmerg:  "059669",
};

const makeShadow = () => ({ type: "outer" as const, blur: 8, offset: 3, angle: 135, color: "000000", opacity: 0.10 });

function addSlideHeader(slide: any, pres: any, title: string, subtitle?: string) {
  slide.addShape(pres.shapes.RECTANGLE, { x: 0, y: 0, w: 10, h: 0.7, fill: { color: C.navy }, line: { color: C.navy } });
  slide.addText("GB  GoodBlue", { x: 0.3, y: 0.08, w: 3, h: 0.5, fontSize: 13, bold: true, color: C.white, fontFace: "Calibri", margin: 0 });
  slide.addText(title, { x: 0.4, y: 0.85, w: 9.2, h: 0.55, fontSize: 22, bold: true, color: C.navy, fontFace: "Calibri", margin: 0 });
  if (subtitle) {
    slide.addText(subtitle, { x: 0.4, y: 1.38, w: 9.2, h: 0.3, fontSize: 11, color: C.gray, fontFace: "Calibri", margin: 0 });
  }
  slide.addShape(pres.shapes.LINE, { x: 0.4, y: subtitle ? 1.65 : 1.38, w: 9.2, h: 0, line: { color: C.lightGray, width: 1 } });
}

function strengthColor(val: string) {
  const v = (val || "").toLowerCase();
  if (v.includes("very strong")) return C.green;
  if (v.includes("strong")) return "16A34A";
  if (v.includes("moderate")) return C.amber;
  if (v.includes("weak")) return C.red;
  return C.gray;
}

function addTitleSlide(pres: any, meta: any) {
  const slide = pres.addSlide();
  slide.background = { color: C.navy };
  slide.addShape(pres.shapes.RECTANGLE, { x: 0, y: 3.8, w: 10, h: 1.825, fill: { color: C.blue }, line: { color: C.blue } });
  slide.addText("GoodBlue", { x: 0.6, y: 0.5, w: 4, h: 0.6, fontSize: 16, bold: true, color: C.lightBlue, fontFace: "Calibri", margin: 0 });
  slide.addText("Competitive Analysis", { x: 0.6, y: 1.3, w: 8.8, h: 1.1, fontSize: 44, bold: true, color: C.white, fontFace: "Calibri", margin: 0 });
  slide.addText(`${meta.company}  ·  ${meta.product}`, { x: 0.6, y: 2.55, w: 8.8, h: 0.5, fontSize: 20, color: C.lightBlue, fontFace: "Calibri", margin: 0 });
  slide.addText(`${meta.market} Market`, { x: 0.6, y: 3.1, w: 8.8, h: 0.35, fontSize: 13, color: C.lightBlue, fontFace: "Calibri", italic: true, margin: 0 });
  slide.addText("Strategy, generated in minutes", { x: 0.6, y: 3.95, w: 8.8, h: 0.4, fontSize: 13, color: C.white, fontFace: "Calibri", margin: 0 });
  slide.addText(`Generated by GoodBlue.ai  ·  ${new Date().toLocaleDateString("en-US", { month: "long", year: "numeric" })}`, { x: 0.6, y: 4.5, w: 8.8, h: 0.35, fontSize: 10, color: C.lightBlue, fontFace: "Calibri", margin: 0 });
}

function addExecSummarySlide(pres: any, slide2: any) {
  const slide = pres.addSlide();
  slide.background = { color: C.offWhite };
  addSlideHeader(slide, pres, "Executive Summary");
  const insights = slide2.KeyInsights || [];
  const startY = 1.8;
  const itemH = 0.72;
  insights.slice(0, 4).forEach((insight: string, i: number) => {
    const y = startY + i * itemH;
    slide.addShape(pres.shapes.OVAL, { x: 0.4, y: y + 0.05, w: 0.38, h: 0.38, fill: { color: C.blue }, line: { color: C.blue } });
    slide.addText(String(i + 1), { x: 0.4, y: y + 0.05, w: 0.38, h: 0.38, fontSize: 12, bold: true, color: C.white, align: "center", valign: "middle", fontFace: "Calibri", margin: 0 });
    slide.addShape(pres.shapes.RECTANGLE, { x: 0.9, y, w: 8.7, h: 0.6, fill: { color: C.white }, line: { color: C.lightGray, width: 0.5 }, shadow: makeShadow() });
    slide.addText(insight, { x: 1.05, y: y + 0.05, w: 8.4, h: 0.5, fontSize: 11.5, color: C.darkText, fontFace: "Calibri", valign: "middle", margin: 0 });
  });
  const takeawayY = startY + insights.slice(0, 4).length * itemH + 0.15;
  slide.addShape(pres.shapes.RECTANGLE, { x: 0.4, y: takeawayY, w: 9.2, h: 0.78, fill: { color: C.navy }, line: { color: C.navy }, shadow: makeShadow() });
  slide.addText("Strategic Takeaway", { x: 0.6, y: takeawayY + 0.06, w: 9, h: 0.22, fontSize: 9, bold: true, color: C.lightBlue, fontFace: "Calibri", charSpacing: 2, margin: 0 });
  slide.addText(slide2.StrategicTakeaway || "", { x: 0.6, y: takeawayY + 0.28, w: 9, h: 0.42, fontSize: 11, color: C.white, fontFace: "Calibri", italic: true, valign: "top", margin: 0 });
}

function addMarketLandscapeSlide(pres: any, slide3: any) {
  const slide = pres.addSlide();
  slide.background = { color: C.offWhite };
  addSlideHeader(slide, pres, "Market Landscape & Positioning", `${slide3.Axes?.XAxis || "Market Reach"} vs ${slide3.Axes?.YAxis || "Capabilities"}`);
  const qx = 0.4, qy = 1.75, qw = 5.8, qh = 3.6;
  const midX = qx + qw / 2, midY = qy + qh / 2;
  slide.addShape(pres.shapes.RECTANGLE, { x: qx, y: qy, w: qw, h: qh, fill: { color: C.white }, line: { color: C.lightGray, width: 1 } });
  slide.addShape(pres.shapes.LINE, { x: midX, y: qy, w: 0, h: qh, line: { color: C.lightGray, width: 1 } });
  slide.addShape(pres.shapes.LINE, { x: qx, y: midY, w: qw, h: 0, line: { color: C.lightGray, width: 1 } });
  const quadColors: any = { Leaders: C.quadLeader, Challengers: C.quadChall, Niche: C.quadNiche, Emerging: C.quadEmerg };
  const quadPositions: any = {
    Leaders:     { x: midX + 0.1, y: qy + 0.1 },
    Challengers: { x: qx + 0.1,   y: qy + 0.1 },
    Niche:       { x: qx + 0.1,   y: midY + 0.1 },
    Emerging:    { x: midX + 0.1, y: midY + 0.1 },
  };
  Object.entries(quadPositions).forEach(([label, pos]: [string, any]) => {
    slide.addText(label, { x: pos.x, y: pos.y, w: 2.5, h: 0.3, fontSize: 9, bold: true, color: quadColors[label] || C.gray, fontFace: "Calibri", margin: 0 });
  });
  slide.addText(slide3.Axes?.XAxis || "Market Reach & Adoption", { x: qx, y: qy + qh + 0.08, w: qw, h: 0.25, fontSize: 9, color: C.gray, align: "center", fontFace: "Calibri", margin: 0 });
  const points = slide3.PlotPoints || [];
  points.forEach((pt: any) => {
    if (typeof pt.x !== "number" || typeof pt.y !== "number") return;
    const clampedX = Math.min(Math.max(pt.x, 0.5), 9.5);
    const clampedY = Math.min(Math.max(pt.y, 0.5), 9.5);
    const px = qx + (clampedX / 10) * qw - 0.18;
    const py = qy + ((10 - clampedY) / 10) * qh - 0.18;
    const dotColor = quadColors[pt.category] || C.blue;
    slide.addShape(pres.shapes.OVAL, { x: px, y: py, w: 0.36, h: 0.36, fill: { color: dotColor }, line: { color: dotColor } });
    slide.addText(pt.name || "", { x: px - 0.3, y: py + 0.35, w: 1.2, h: 0.25, fontSize: 7.5, color: C.darkText, align: "center", fontFace: "Calibri", margin: 0 });
  });
  const obs = slide3.Observations || [];
  slide.addText("Key Observations", { x: 6.4, y: 1.75, w: 3.3, h: 0.3, fontSize: 11, bold: true, color: C.navy, fontFace: "Calibri", margin: 0 });
  obs.slice(0, 5).forEach((o: string, i: number) => {
    const oy = 2.15 + i * 0.65;
    slide.addShape(pres.shapes.RECTANGLE, { x: 6.4, y: oy, w: 0.04, h: 0.42, fill: { color: C.blue }, line: { color: C.blue } });
    slide.addText(o, { x: 6.55, y: oy, w: 3.1, h: 0.5, fontSize: 9, color: C.darkText, fontFace: "Calibri", valign: "top", margin: 0 });
  });
}

function addHeadToHeadSlide(pres: any, slide4: any) {
  const slide = pres.addSlide();
  slide.background = { color: C.offWhite };
  addSlideHeader(slide, pres, "Head-to-Head Comparison");
  const table = slide4.Table || {};
  const cols = table.Columns || [];
  const rows = table.Rows || [];
  if (cols.length === 0 || rows.length === 0) return;
  const companies = cols.slice(1);
  const colW = [2.2, ...companies.map(() => (7.4 / companies.length))];
  const headerRow = cols.map((col: string, i: number) => ({
    text: col,
    options: { fill: { color: i === 0 ? C.navy : C.blue }, color: C.white, bold: true, fontSize: 10, fontFace: "Calibri", align: i === 0 ? "left" : "center", valign: "middle" }
  }));
  const tableData = [headerRow];
  rows.slice(0, 5).forEach((row: any, ri: number) => {
    const rowBg = ri % 2 === 0 ? C.white : "F1F5F9";
    const dataRow = cols.map((col: string, ci: number) => {
      if (ci === 0) return { text: row.Capability || "", options: { fill: { color: rowBg }, bold: true, fontSize: 9.5, fontFace: "Calibri", color: C.darkText, align: "left", valign: "middle" } };
      const val = row.Values?.[col] || "-";
      return { text: val, options: { fill: { color: rowBg }, fontSize: 8.5, fontFace: "Calibri", color: strengthColor(val), align: "center", valign: "middle" } };
    });
    tableData.push(dataRow);
  });
  slide.addTable(tableData, { x: 0.4, y: 1.75, w: 9.2, h: 3.3, colW, border: { pt: 0.5, color: C.lightGray }, rowH: 3.3 / (rows.slice(0, 5).length + 1) });
  if (slide4.Takeaway) {
    slide.addShape(pres.shapes.RECTANGLE, { x: 0.4, y: 5.15, w: 9.2, h: 0.35, fill: { color: C.lightBlue }, line: { color: C.lightBlue } });
    slide.addText(`► ${slide4.Takeaway}`, { x: 0.55, y: 5.17, w: 9, h: 0.3, fontSize: 9.5, color: C.navy, fontFace: "Calibri", italic: true, margin: 0 });
  }
}

function addDeepDiveSlide(pres: any, slide5: any) {
  const slide = pres.addSlide();
  slide.background = { color: C.offWhite };
  addSlideHeader(slide, pres, `Deep Dive: ${slide5.Company || "Key Competitor"}`, slide5.Positioning || "");
  const swot = slide5.SWOT || {};
  const quadrants = [
    { label: "Strengths",     items: swot.Strengths || [],     bg: "DCFCE7", accent: "16A34A", prefix: "+" },
    { label: "Weaknesses",    items: swot.Weaknesses || [],    bg: "FEE2E2", accent: C.red,    prefix: "−" },
    { label: "Opportunities", items: swot.Opportunities || [], bg: "DBEAFE", accent: C.blue,   prefix: "↑" },
    { label: "Threats",       items: swot.Threats || [],       bg: "FEF3C7", accent: C.amber,  prefix: "!" },
  ];
  const cardW = 4.45, cardH = 1.65;
  const positions = [{ x: 0.4, y: 1.85 }, { x: 5.15, y: 1.85 }, { x: 0.4, y: 3.6 }, { x: 5.15, y: 3.6 }];
  quadrants.forEach((q, i) => {
    const pos = positions[i];
    slide.addShape(pres.shapes.RECTANGLE, { x: pos.x, y: pos.y, w: cardW, h: cardH, fill: { color: q.bg }, line: { color: q.accent, width: 1 }, shadow: makeShadow() });
    slide.addShape(pres.shapes.RECTANGLE, { x: pos.x, y: pos.y, w: 0.06, h: cardH, fill: { color: q.accent }, line: { color: q.accent } });
    slide.addText(q.label, { x: pos.x + 0.15, y: pos.y + 0.08, w: cardW - 0.2, h: 0.28, fontSize: 11, bold: true, color: q.accent, fontFace: "Calibri", margin: 0 });
    const bulletItems = q.items.slice(0, 3).map((item: string, bi: number) => ({
      text: `${q.prefix}  ${item}`,
      options: { breakLine: bi < q.items.slice(0, 3).length - 1, fontSize: 9, color: C.darkText }
    }));
    if (bulletItems.length > 0) slide.addText(bulletItems, { x: pos.x + 0.15, y: pos.y + 0.38, w: cardW - 0.25, h: cardH - 0.48, fontFace: "Calibri", valign: "top", margin: 0 });
  });
  if (slide5.StrategicImplication) {
    slide.addShape(pres.shapes.RECTANGLE, { x: 0.4, y: 5.33, w: 9.2, h: 0.22, fill: { color: C.navy }, line: { color: C.navy } });
    slide.addText(`Strategic Implication:  ${slide5.StrategicImplication}`, { x: 0.55, y: 5.34, w: 9, h: 0.2, fontSize: 8.5, color: C.white, fontFace: "Calibri", italic: true, margin: 0 });
  }
}

function addWhiteSpaceSlide(pres: any, slide6: any) {
  const slide = pres.addSlide();
  slide.background = { color: C.offWhite };
  addSlideHeader(slide, pres, "Strategic White Space");
  slide.addShape(pres.shapes.RECTANGLE, { x: 0.4, y: 1.75, w: 4.2, h: 3.45, fill: { color: C.white }, line: { color: C.lightGray }, shadow: makeShadow() });
  slide.addShape(pres.shapes.RECTANGLE, { x: 0.4, y: 1.75, w: 4.2, h: 0.38, fill: { color: C.gray }, line: { color: C.gray } });
  slide.addText("What Exists Today", { x: 0.5, y: 1.78, w: 4, h: 0.32, fontSize: 11, bold: true, color: C.white, fontFace: "Calibri", margin: 0 });
  const today = slide6.WhatExistsToday || [];
  const todayItems = today.slice(0, 4).map((t: string, i: number) => ({ text: `•  ${t}`, options: { breakLine: i < today.slice(0, 4).length - 1, fontSize: 10, color: C.darkText } }));
  if (todayItems.length > 0) slide.addText(todayItems, { x: 0.55, y: 2.2, w: 3.9, h: 2.8, fontFace: "Calibri", valign: "top", margin: 0 });
  slide.addShape(pres.shapes.RECTANGLE, { x: 4.8, y: 1.75, w: 4.8, h: 3.45, fill: { color: C.white }, line: { color: C.lightGray }, shadow: makeShadow() });
  slide.addShape(pres.shapes.RECTANGLE, { x: 4.8, y: 1.75, w: 4.8, h: 0.38, fill: { color: C.blue }, line: { color: C.blue } });
  slide.addText("What Leaders Need", { x: 4.9, y: 1.78, w: 4.6, h: 0.32, fontSize: 11, bold: true, color: C.white, fontFace: "Calibri", margin: 0 });
  const needs = slide6.WhatLeadersNeed || [];
  const needItems = needs.slice(0, 4).map((n: string, i: number) => ({ text: `→  ${n}`, options: { breakLine: i < needs.slice(0, 4).length - 1, fontSize: 10, color: C.darkText } }));
  if (needItems.length > 0) slide.addText(needItems, { x: 4.95, y: 2.2, w: 4.5, h: 2.8, fontFace: "Calibri", valign: "top", margin: 0 });
  slide.addShape(pres.shapes.RECTANGLE, { x: 0.4, y: 5.3, w: 9.2, h: 0.22, fill: { color: C.navy }, line: { color: C.navy } });
  slide.addText(`White Space:  ${slide6.WhiteSpaceOpportunity || ""}`, { x: 0.55, y: 5.31, w: 9, h: 0.2, fontSize: 8.5, color: C.white, fontFace: "Calibri", italic: true, margin: 0 });
}

function addNextStepsSlide(pres: any, slide7: any) {
  const slide = pres.addSlide();
  slide.background = { color: C.offWhite };
  addSlideHeader(slide, pres, "Next Steps");
  const sections = [
    { label: "Immediate (0–90 Days)", items: slide7.Immediate_0_90_Days || [], color: C.blue, bg: "EFF6FF" },
    { label: "Mid-Term",              items: slide7.MidTerm || [],             color: C.teal, bg: "F0FDFA" },
    { label: "Avoid",                 items: slide7.Avoid || [],               color: C.red,  bg: "FEF2F2" },
  ];
  sections.forEach((sec, i) => {
    const x = 0.4 + i * 3.15;
    slide.addShape(pres.shapes.RECTANGLE, { x, y: 1.75, w: 2.95, h: 3.45, fill: { color: sec.bg }, line: { color: sec.color, width: 1 }, shadow: makeShadow() });
    slide.addShape(pres.shapes.RECTANGLE, { x, y: 1.75, w: 2.95, h: 0.42, fill: { color: sec.color }, line: { color: sec.color } });
    slide.addText(sec.label, { x: x + 0.1, y: 1.78, w: 2.75, h: 0.36, fontSize: 10, bold: true, color: C.white, fontFace: "Calibri", margin: 0 });
    const bulletItems = sec.items.slice(0, 3).map((item: string, bi: number) => ({ text: item, options: { bullet: true, breakLine: bi < sec.items.slice(0, 3).length - 1, fontSize: 9.5, color: C.darkText } }));
    if (bulletItems.length > 0) slide.addText(bulletItems, { x: x + 0.1, y: 2.25, w: 2.75, h: 2.85, fontFace: "Calibri", valign: "top", margin: 0 });
  });
  if (slide7.ExecutionNote) {
    slide.addShape(pres.shapes.RECTANGLE, { x: 0.4, y: 5.3, w: 9.2, h: 0.22, fill: { color: C.navy }, line: { color: C.navy } });
    slide.addText(`Note:  ${slide7.ExecutionNote}`, { x: 0.55, y: 5.31, w: 9, h: 0.2, fontSize: 8.5, color: C.white, fontFace: "Calibri", italic: true, margin: 0 });
  }
}

function addSourcesSlide(pres: any, slide8: any) {
  const slide = pres.addSlide();
  slide.background = { color: C.navy };
  slide.addText("Sources & Methodology", { x: 0.6, y: 0.5, w: 8.8, h: 0.7, fontSize: 28, bold: true, color: C.white, fontFace: "Calibri", margin: 0 });
  slide.addShape(pres.shapes.RECTANGLE, { x: 0.6, y: 1.4, w: 8.8, h: 2.6, fill: { color: "1E3A5F" }, line: { color: "1E3A5F" } });
  slide.addText("Methodology", { x: 0.8, y: 1.55, w: 8.4, h: 0.3, fontSize: 11, bold: true, color: C.lightBlue, fontFace: "Calibri", margin: 0 });
  const methods = slide8.Method || [];
  const methodItems = methods.slice(0, 4).map((m: string, i: number) => ({ text: m, options: { bullet: true, breakLine: i < methods.slice(0, 4).length - 1, fontSize: 10, color: C.white } }));
  if (methodItems.length > 0) slide.addText(methodItems, { x: 0.8, y: 1.92, w: 8.4, h: 1.95, fontFace: "Calibri", valign: "top", margin: 0 });
  if (slide8.Disclaimer) slide.addText(slide8.Disclaimer, { x: 0.6, y: 4.2, w: 8.8, h: 0.6, fontSize: 9, color: C.lightBlue, fontFace: "Calibri", italic: true, valign: "top", margin: 0 });
  slide.addText("GoodBlue.ai  ·  Strategy, generated in minutes", { x: 0.6, y: 5.1, w: 8.8, h: 0.3, fontSize: 9, color: C.gray, fontFace: "Calibri", margin: 0 });
}

export async function POST(req: NextRequest) {
  try {
    const deck = await req.json();

    const meta = deck.meta || {};
    const s2   = deck.Slide2_ExecutiveSummary         || {};
    const s3   = deck.Slide3_MarketLandscape          || {};
    const s4   = deck.Slide4_HeadToHead               || {};
    const s5   = deck.Slide5_Competitor_DeepDive_SWOT || {};
    const s6   = deck.Slide6_StrategicWhiteSpace      || {};
    const s7   = deck.Slide7_NextSteps                || {};
    const s8   = deck.Slide8_Sources_Methodology      || {};

    const pres = new pptxgen();
    pres.layout = "LAYOUT_16x9";
    pres.title  = `GoodBlue Competitive Analysis – ${meta.company || ""}`;
    pres.author = "GoodBlue.ai";

    addTitleSlide(pres, meta);
    addExecSummarySlide(pres, s2);
    addMarketLandscapeSlide(pres, s3);
    addHeadToHeadSlide(pres, s4);
    addDeepDiveSlide(pres, s5);
    addWhiteSpaceSlide(pres, s6);
    addNextStepsSlide(pres, s7);
    addSourcesSlide(pres, s8);

    const buffer = await pres.write({ outputType: "nodebuffer" }) as Buffer;
    const uint8Array = new Uint8Array(buffer);

    return new NextResponse(uint8Array, {
      status: 200,
      headers: {
        "Content-Type": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "Content-Disposition": `attachment; filename="GoodBlue_${meta.company || "Analysis"}_Competitive_Analysis.pptx"`,
      },
    });
  } catch (err) {
    console.error("PPTX generation error:", err);
    return NextResponse.json({ error: "Failed to generate PPTX" }, { status: 500 });
  }
}
